package io.github.lucfr1746.LSurvivalLib.Enchantments;

public enum Enchantment {
    ANGLER,
    AQUA_AFFINITY,
    /* done */    BANE_OF_ARTHROPODS,
    BIG_BRAIN,
    BLAST_PROTECTION,
    BLESSING,
    CASTER,
    CAYENNE,
    CHAMPION,
    CHANCE,
    CHARM,
    /* done */    CLEAVE,
    COMPACT,
    CORRUPTION,
    COUNTER_STRIKE,
    /* done */    CRITICAL,
    /* done */    CUBISM,
    CULTIVATING,
    DEDICATION,
    DELICATE,
    DEPTH_STRIDER,
    /* done */    DIVINE_GIFT,
    /* done */    DRAGON_HUNTER,
    DRAGON_TRACER,
    EFFICIENCY,
    /* done */    ENDER_SLAYER,
    /* done */    EXECUTE,
    /* done */    EXPERIENCE,
    EXPERTISE,
    FEATHER_FALLING,
    FEROCIOUS_MANA,
    /* done */    FIRE_ASPECT,
    FIRE_PROTECTION,
    /* done */    FIRST_STRIKE,
    FLAME,
    FORTUNE,
    FRAIL,
    FROST_WALKER,
    /* done */    GIANT_KILLER,
    GROWTH,
    HARDENED_MANA,
    HARVESTING,
    /* done */    IMPALING,
    INFINITE_QUIVER,
    /* done */    KNOCKBACK,
    /* done */    LETHALITY,
    /* done */    LIFE_STEAL,
    /* done */    LOOTING,
    /* done */    LUCK,
    LUCK_OF_THE_SEA,
    LURE,
    MAGNET,
    /* done */    MANA_STEAL,
    MANA_VAMPIRE,
    OVERLOAD,
    PIERCING,
    PISCARY,
    POWER,
    PROJECTILE_PROTECTION,
    /* done */    PROSECUTE,
    PROSPERITY,
    PROTECTION,
    PUNCH,
    QUANTUM,
    RAINBOW,
    REFLECTION,
    REJUVENATE,
    REPLENISH,
    RESPIRATION,
    RESPITE,
    /* done */    SCAVENGER,
    /* done */    SHARPNESS,
    SILK_TOUCH,
    SMARTY_PANTS,
    SMELTING_TOUCH,
    /* done */    SMITE,
    /* done */    SMOLDERING,
    SNIPE,
    SPIKED_HOOK,
    STRONG_MANA,
    SUGAR_RUSH,
    SUNDER,
    /* done */    SYPHON,
    /* done */    TABASCO,
    THORNS,
    /* done */    THUNDERBOLT,
    /* done */    THUNDERLORD,
    /* done */    TITAN_KILLER,
    TOXOPHILITE,
    TRANSYLVANIAN,
    /* done */    TRIPLE_STRIKE,
    TRUE_PROTECTION,
    TURBO_CACTI,
    TURBO_CANE,
    TURBO_CARROT,
    TURBO_COCOA,
    TURBO_MELON,
    TURBO_MUSHROOMS,
    TURBO_POTATO,
    TURBO_PUMPKIN,
    TURBO_WARTS,
    TURBO_WHEAT,
    /* done */    VAMPIRISM,
    /* done */    VENOMOUS,
    /* done */    VICIOUS,
}
